application/flask_blog/models/entries.py
from flask_blog import db
from datetime import datetime


class Entry(db.Model):
    __tabelename__ = "entries"
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(50), unique=True)
    text = db.Column(db.Text)
    created_at = db.Column(db.DateTime)

    def __init__(self, title=None, text=None):
        self.title = title
        self.text = text
        self.created_at = datetime.utcnow()

    def __repr__(self):
        return '<Entry id:{} title:{} text:{}>'.format(self.id, self.title, self.text)

application/flask_blog/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()


def create_app(test_config=None):
    app = Flask(__name__)
    app.config.from_object('flask_blog.config')

    if test_config:
        app.config.from_mapping(test_config)

    db.init_app(app)

    from flask_blog.views.views import view
    app.register_blueprint(view)

    from flask_blog.views.entries import entry
    app.register_blueprint(entry, url_prefix="/users")

    return app

application/flask_blog/views.py
from flask import request, redirect, url_for, render_template, flash, session
from flask_blog import app


@app.route('/')
def show_entries():
    if not session.get("logged_in"):
        return redirect(url_for("login"))
    return render_template("entries/index.html")


@app.route('/login', methods=['GET', 'POST'])
def login():
    error = None
    if request.method == "POST":
        if request.form['username'] != app.config["USERNAME"]:
            flash("ユーザー名が異なります")
        elif request.form["password"] != app.config["PASSWORD"]:
            flash("パスワードが異なります")
        else:
            session["logged_in"] = True
            flash("ログインしました")
            return redirect(url_for("show_entries"))
    return render_template("login.html")


@app.route("/logout")
def logout():
    session.pop("logged_in", None)
    flash("ログアウトしました")
    return redirect(url_for("show_entries"))

application/flask_blog/views/entries.py
from flask import request, redirect, url_for, render_template, flash, session
from flask import current_app as app
from flask_blog import db
from flask_blog.models.entries import Entry
from flask_blog.views.views import login_required
from flask import Blueprint

entry = Blueprint('entry', __name__)


@entry.route("/")
@login_required
def show_entries():
    entries = Entry.query.order_by(Entry.id.desc()).all()
    return render_template("entries/index.html", entries=entries)


@entry.route("/entries", methods=["POST"])
@login_required
def add_entry():
    entry = Entry(
        title=request.form["title"],
        text=request.form["text"]
    )
    db.session.add(entry)
    db.session.commit()
    flash("新しく記事が作成されました")
    return redirect(url_for('entry.show_entries'))


@entry.route("/entries/new", methods=["GET"])
@login_required
def new_entry():
    return render_template("entries/new.html")


@entry.route("/entries/<int:id>", methods=["GET"])
@login_required
def show_entry(id):
    entry = Entry.query.get(id)
    return render_template('entries/show.html', entry=entry)


@entry.route("/entries/<int:id>/edit", methods=["GET"])
@login_required
def edit_entry(id):
    entry = Entry.query.get(id)
    return render_template("entries/edit.html", entry=entry)


@entry.route("/entries/<int:id>/update", methods=["POST"])
@login_required
def update_entry(id):
    entry = Entry.query.get(id)
    entry.title = request.form["title"]
    entry.text = request.form["text"]
    db.session.merge(entry)
    db.session.commit()
    flash("記事が更新されました")
    return redirect(url_for("entry.show_entries"))


@entry.route("/entries/<int:id>/delete", methods=["POST"])
@login_required
def delete_entry(id):
    entry = Entry.query.get(id)
    db.session.delete(entry)
    db.session.commit()
    flash("投稿が削除されました")
    return redirect(url_for("entry.show_entries"))

application/flask_blog/views/views.py
from flask import request, redirect, url_for, render_template, flash, session
from flask import current_app as app
from functools import wraps
from flask import Blueprint


view = Blueprint("view", __name__)


def login_required(view):
    """
    ログイン機能画面への遷移
    """
    @wraps(view)
    def inner(*args, **kwargs):
        if not session.get('logged_in'):
            return redirect(url_for('view.login'))
        return view(*args, **kwargs)
    return inner


@view.route('/login', methods=['GET', 'POST'])
def login():
    error = None
    if request.method == "POST":
        if request.form['username'] != app.config["USERNAME"]:
            flash("ユーザー名が異なります")
        elif request.form["password"] != app.config["PASSWORD"]:
            flash("パスワードが異なります")
        else:
            session["logged_in"] = True
            flash("ログインしました")
            return redirect(url_for("entry.show_entries"))
    return render_template("login.html")


@view.route("/logout")
def logout():
    session.pop("logged_in", None)
    flash("ログアウトしました")
    return redirect(url_for("entry.show_entries"))


@view.app_errorhandler(404)
def non_existant_route(error):
    flash("404エラー: ログイン画面に移動します")
    return redirect(url_for("view.login"))

application/flask_blog/templates/entries/edit.html
{% extends 'layout.html' %}
{% block body %}
<form action="{{ url_for('entry.update_entry', id=entry.id) }}" method=post class=add-entry>
    <div class="form-group">
        <label for="InputTitle">タイトル</label>
        <input type="text" class="form-control" id="InputTitle" name=title value={{ entry.title}}>
    </div>
    <div class="form-group">
        <label for="InputText">本文</label>
        <textarea class="form-control" id="InputText" , name=text rows="3">{{ entry.text | safe }}</textarea>
    </div>
    <button type="submit" class="btn btn-primary">更新</button>
</form>

{% endblock %}

application/flask_blog/templates/entries/index.html
{% extends "layout.html" %}
{% block body %}
<ul class="list-group list-group-flush">

    {% for entry in entries %}
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">{{ entry.title }}</h5>
            <a href="{{ url_for('entry.show_entry', id=entry.id) }}" class="card-link">続きを読む</a>
        </div>
    </div>
    {% else %}
    投稿がありません
    {% endfor %}
</ul>

{% endblock %}

application/flask_blog/templates/entries/new.html
{% extends 'layout.html' %}
{% block body %}
<form action="{{ url_for('entry.add_entry') }}" method=post class=add-entry>
    <div class="form-group">
        <label for="InputTitle">タイトル</label>
        <input type="text" class="form-control" id="InputTitle" name=title>
    </div>

    <div class="form-group">
        <label for="InputText">本文</label>
        <textarea class="form-control" id="InputText" name=text rows="3"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">作成</button>
</form>
{% endblock %}

application/flask_blog/templates/entries/show.html
{% extends 'layout.html' %}
{% block body %}

<h2>{{ entry.title }}</h2>
<br>{{ entry.text|safe }}

<br>
<br> 投稿日時 {{ entry.created_at }}

<br>
<br>

<div class="btn-group">
    <form action="{{ url_for('entry.edit_entry', id=entry.id) }}" method="GET">
        <button type="submit" class="btn btn-secondary">編集</button>
    </form>

    <form action="{{ url_for('entry.delete_entry', id=entry.id) }}" method="post">
        <button type="submit" class="btn btn-danger" style="margin-left:5px">削除</button>
    </form>
</div>

{% endblock %}

application/flask_blog/templates/layout.html
<!DOCTYPE html>
<title>Flask Blog</title>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<link href="https://fonts.googleapis.com/earlyaccess/mplus1p.css" rel="stylesheet" type="text/css">
<link rel=stylesheet href="{{ url_for('static', filename='style.css') }}">

<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Flask FAVMAP</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle-navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="nav navbar-nav navbar-right">
                {% if not session.logged_in %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('view.login') }}">ログイン</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('entry.new_entry')}}">新規投稿</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('view.logout') }}">ログアウト</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    {% for message in get_flashed_messages() %}
    <div class="alert alert-info" role="alert">
        {{ message }}
    </div>
    {% endfor %}

    <div class="blog-body">
        {% block body %}{% endblock %}
    </div>
</div>

application/flask_blog/templates/login.html
{% extends "layout.html" %}
{% block body %}
<form action="{{ url_for('view.login') }}" method=post>
    <div class="form-group">
        <label for="InputTitle">ユーザー名</label>
        <input type="text" class="form-control" id="InputTitle" name=username>
    </div>

    <div class="form-group">
        <label for="InputPassword">パスワード</label>
        <input type="password" class="form-control" id="InputPassword" name=password>
    </div>
    <button type="submit" class="btn btn-primary">ログイン</button>
</form>
{% endblock %}